config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  get '/about', to: 'pages#about'
  resources :contacts, only: [:create]
  resources :users do
    resource :profile
  end
    
  get '/contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :comment, length: { in: 5..300 }
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :users
end

app/models/profile.rb
class Profile < ApplicationRecord
  
  belongs_to :user
  
  # Profile avatar
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  validates :fname, :lname, presence: true
  validates :description, length: {in: 5..100}
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :plan
  has_one :profile
  
  attr_accessor :stripe_card_token
  def save_with_subscription
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id 
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  #Whitelisting in custom forms occurs in this controller according to
  #Devise documentation
  protected 
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation)}
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end 
  
  def create
    #creates contact object with mass assignment
    @contact = Contact.new( contact_params )
    
    if @contact.save
      #Save to contacts table in database
      redirect_to root_path
      flash[:success] = "Successfully sent your question"
    else
      #Redirect to empty form
      redirect_to new_contact_path
      flash[:danger] = "Error: " + @contact.errors.full_messages.join(", ")
    end
  end
  
  #Whitelisting form fields as best practice security feature 
  def contact_params
    params.require(:contact).permit(:name, :email, :comment)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  #GET request to root_path ('/')
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end
  
  def about
    
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_action :authenticate_user!
  before_action :only_current_user
  
  def new
    #Users already with a profile gets redirected
    if !current_user.profile
      @profile = Profile.new
    else 
      flash[:notice] = "You already have a profile"
      redirect_to root_path
    end
  end
  
  def create
    
    @user = User.find( params[:user_id])
    #build_association method comes from the "has_one" relationsship  
    @profile = @user.build_profile( profile_parameters )
    
    if @profile.save
      flash[:success] = 'Successfully created profile'
      redirect_to root_path
    else
      #Error messages
      render action: :new
      flash[:danger] = @profile.errors.full_messages.join(", ")
    end
    
  end
  
  #GET to /Users/:id/profile/edit
  def edit
    @profile = User.find( params[:user_id] ).profile
  end
  
  #PUT/PATch request to /Users/:id/profile/edit
  def update
    @profile = User.find( params[:user_id] ).profile
    if @profile.update_attributes( profile_parameters )
      flash[:success] = 'Successfully updated profile info'
      #show user
      redirect_to user_path( id: current_user.id )
    else
      flash[:danger] = @profile.errors.full_messages.join(', ')
      render action: :edit
    end
  end
  
  private 
    def profile_parameters
      params.require(:profile).permit(:fname, :lname, :avatar, :title, :description) 
    end
  
    def only_current_user
      @user = User.find( params[:user_id] )
      redirect_to root_path unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  def create
    
    #Extend Devise create action
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
    
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :check_for_profile, only: :show
  
  #GET request to users/:id
  def show
    @user = User.find(params[:id])
  end
  
  #GET request to users
  def index
    #SQL join (all Users and include all profiles)
    @users = User.includes(:profile)
  end
  
  protected 
    def check_for_profile
      if !User.find(params[:id]).profile 
        flash[:danger] = 'This user has not created a profile'
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center">Contact Us</h1>
    <p class="text-center">Send us an email for questions or thoughts about the site</p>
    <div class="col-md-6 col-md-offset-3">
      <div class="well">
        <%= form_for @contact do |f| %>
          <div class="form-group">
            <%= f.label :name, 'Name' %>
            <%= f.text_field :name, class: 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.label :email, 'Email' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :comment, 'Question' %>
            <%= f.text_area :comment, class: 'form-control' %>
          </div>
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
    
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/" class="navbar-brand"><i class="fa fa-bath" aria-hidden="true"></i> The Pond</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if user_signed_in? %>
            <%= link_to 'Log out',  destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn navbar-right' %>
          <% else%> 
            <%= link_to 'Log in',  new_user_session_path, class: 'btn btn-default navbar-btn navbar-right' %>
          <% end %> 
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'About', '/about' %></li>
            <li><%= link_to 'Contact us', new_contact_path %></li>
          </ul>
          </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    
    <div class="container flash-container text-center">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    <%= yield %>
    
  </body>
</html>

app/views/pages/_profiles.html.erb
<div class="col-md-4 col-md-offset-2 text-center">
  <div class="well">
    <% if current_user.profile %>
      <%= link_to 'View your profile', user_path(id: current_user.id), class: 'btn btn-default btn-block btn-lg' %>
      <%= link_to 'Edit your profile', edit_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-block btn-lg' %> 
    <% else %>
      <%= link_to 'Create profile', new_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-block btn-lg' %> 
    <% end %> 
  </div>
</div>
<div class="col-md-4 text-center">
  <div class="well">
    <%= link_to 'Access the Community', users_path, class: 'btn btn-default btn-lg btn-block' %>
  </div>
</div>

app/views/pages/_signup.html.erb
<div class="col-md-5 col-md-offset-1 text-center">
  <div class="well">
    <h2>Basic</h2>
    <p>Sign up with the basic plan for free to get access to the community</p>
    <%= link_to 'Basic', new_user_registration_path(:plan => @basic_plan.id), class: 'btn btn-primary btn-block btn-lg' %>
  </div>
</div>
<div class="col-md-5 text-center">
  <div class="well">
    <h2>Pro</h2>
    <p>Sign up with the Pro plan for 10$/month for community access and access to contact information</p>
    <%= link_to 'Pro', new_user_registration_path(:plan => @pro_plan.id), class: 'btn btn-success btn-block btn-lg' %>
  </div>
</div>

app/views/pages/about.html.erb
<div class="text-center">
  <h2>About</h2>
  <p>The pond is a fictional social meeting point for different fish to meet and exchange contact information </p>
</div>

app/views/pages/home.html.erb
<div class="container-fluid home-callout text-center">
  <h1>Welcome to The Pond</h1>
  <h3>A meetup site for developers and entrepeneurs</h3>
</div>
<div class="container sign-up-fields">
  <div class="row">
    <% if !user_signed_in? %> 
      <%= render 'signup' %>
    <% else %> 
      <%= render 'profiles' %> 
    <% end %> 
  </div>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, html: {multipart: true} do |f| %> 
  <div class="form-group">
    <%= label_tag :fname, 'First Name' %>
    <%= f.text_field :fname, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= label_tag :lname, 'Last Name' %>
    <%= f.text_field :lname, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= label_tag :avatar, 'Profile picture' %>
    <%= f.file_field :avatar %>
  </div>
  
  <div class="form-group">
    <%= label_tag :title, 'Job title' %>
    <%= f.select :title, ['Developer', 'Entrepeneur', 'Student'], class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= label_tag :description, 'Description' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.submit 'Submit profile', class: 'btn btn-success' %>
  </div>
<% end %> 

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-2">
      <h1 class="text-center">Edit your profile</h1>
      <div class="well">
        
        <%= render 'form' %>
        
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-2">
      <h1>Create your profile</h1>
      <div class="well">
        
        <%= form_for @profile, url: user_profile_path do |f| %> 
          <div class="form-group">
            <%= label_tag :fname, 'First Name' %>
            <%= f.text_field :fname, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= label_tag :lname, 'Last Name' %>
            <%= f.text_field :lname, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= label_tag :title, 'Job title' %>
            <%= f.select :title, ['Developer', 'Entrepeneur', 'Student'], class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= label_tag :description, 'Description' %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.submit 'Submit profile', class: 'btn btn-success' %>
          </div>
        <% end %> 
        
      </div>
    </div>
  </div>
</div>

app/views/users/_personal.html.erb
<h2 class="text-center">Want to make changes to your account?</h2>
<div class="row">
  <div class="col-sm-4 col-sm-offset-2">
    <%= link_to 'Edit profile', edit_user_profile_path(user_id: current_user.id), class: 'btn btn-lg btn-primary profile-btn' %>
  </div>
  <div class="col-sm-4">
    <%= link_to 'Upgrade to pro', '#', class: 'btn btn-lg btn-success profile-btn' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center community-logo">Community</h1>
      <ul class="list-unstyled">
        <% @users.each do |u| %>
          <% if u.profile %>
            <li>
              <div class="row well <%= cycle('white-bg', ' ') %>">
                <div class="col-sm-3">
                  <%= image_tag u.profile.avatar.url, class: 'profile-avatar' %>
                </div>
                <div class="col-sm-6">
                  <%= link_to u, class: 'profile-name-link' do %>
                    <h3><%= u.profile.fname + " " + u.profile.lname %></h3>
                  <% end %>
                  <p><%= u.profile.title %></p>
                </div>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 col-md-offset-1">
      <%= image_tag @user.profile.avatar.url, class: 'profile-avatar' %>
    </div>
    <div class="col-md-6">
      <h1><%= @user.profile.fname + " " + @user.profile.lname %></h1>
      <h3><%= @user.profile.title %></h3><br/>
      <div class="well profile-basic-info">
        <h3>About Me</h3>
        <p><%= @user.profile.description %></p>
      </div>
      <% if current_user.plan_id == 2 || @user == current_user %>
        <div class="well profile-contact-info">
          <h3>Contact Me</h3>
          <p><%= @user.email%></p>
        </div>
      <% end %>
      <% # Users visiting their own page get increased functionality %>
      <% if @user == current_user %>
        <%= render 'personal' %>
      <% end %>
    </div>
  </div> 
</div>